# Generated by Django 4.2.7 on 2026-04-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudComplianceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compliant', models.BooleanField(default=False, verbose_name='Соответствует')),
                ('compliance_level', models.IntegerField(default=0, verbose_name='Уровень соответствия (%)')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Последняя проверка')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Сырые данные')),
            ],
            options={
                'verbose_name': 'Соответствие облака протоколу',
                'verbose_name_plural': 'Соответствие облаков протоколам',
                'ordering': ['cloud', 'protocol__category', 'protocol'],
            },
        ),
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('region', models.CharField(default='RU', max_length=50, verbose_name='Регион')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Облачный провайдер',
                'verbose_name_plural': 'Облачные провайдеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.CharField(max_length=50, unique=True, verbose_name='ID протокола')),
                ('name', models.CharField(max_length=200, verbose_name='Название протокола')),
                ('category', models.CharField(choices=[('STORAGE', 'Хранилища данных'), ('IAM', 'Управление доступом'), ('SLA', 'Соглашение об уровне обслуживания'), ('ENCRYPTION', 'Шифрование'), ('NETWORK', 'Сетевая безопасность'), ('COMPLIANCE', 'Соответствие стандартам')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('standard', models.CharField(blank=True, max_length=100, verbose_name='Стандарт')),
                ('severity_on_fail', models.CharField(choices=[('CRITICAL', 'Критический'), ('HIGH', 'Высокий'), ('MEDIUM', 'Средний'), ('WARNING', 'Предупреждение')], default='WARNING', max_length=20, verbose_name='Критичность при нарушении')),
                ('remediation_template', models.TextField(verbose_name='Шаблон рекомендации')),
                ('responsibility', models.CharField(choices=[('provider', 'Поставщик'), ('consumer', 'Потребитель'), ('shared', 'Совместная')], default='consumer', max_length=20, verbose_name='Ответственность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Протокол безопасности',
                'verbose_name_plural': 'Протоколы безопасности',
                'ordering': ['category', 'priority'],
            },
        ),
        migrations.DeleteModel(
            name='SecurityCheckRule',
        ),
        migrations.DeleteModel(
            name='TestDataset',
        ),
        migrations.AlterField(
            model_name='testprotocol',
            name='tester_name',
            field=models.CharField(default='Петров Виктор', max_length=100, verbose_name='Тестировщик'),
        ),
        migrations.AddField(
            model_name='cloudcompliancedata',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_data', to='security_checker.cloudprovider', verbose_name='Облако'),
        ),
        migrations.AddField(
            model_name='cloudcompliancedata',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_data', to='security_checker.securityprotocol', verbose_name='Протокол'),
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security_checker.cloudprovider', verbose_name='Облако'),
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='selected_protocols',
            field=models.ManyToManyField(to='security_checker.securityprotocol', verbose_name='Выбранные протоколы'),
        ),
        migrations.AlterUniqueTogether(
            name='cloudcompliancedata',
            unique_together={('cloud', 'protocol')},
        ),
    ]
